### ISSUE TITLE
Error in readme file

### ISSUE THREAD

**Issue by kvyaswanth** [CharonWangg/LearningCausalDiscovery#1]
Need to change [here](https://github.com/KordingLab/LearningCausalDiscovery/blob/main/README.md#learning-procedure): 

from
`python run/scripts/make_csv.py`
to
`python run/scripts/csv_generation.py`

file @ [csv_generation.py](https://github.com/KordingLab/LearningCausalDiscovery/blob/main/run/scripts/csv_generation.py)

**Comment by CharonWangg** [comment]
Thank you! Actually the code for it has been changed a lot but haven't been pushed, will update soon!
